### ISSUE TITLE
Consider feature-by-feature folder layout and component naming

### ISSUE THREAD

**Issue by jimthedev** [bkinsey808/bk-fullstack-ts#3]
I'd like to propose that this project be change to use the following scheme:

```
import { Header } from './header/header';

<to>

import { HeaderComponent } from './layout/header/header.component';

<or to>

import { HeaderComponent } from './layout/header.component';
```

Then your app's business domain objects would look like this no matter where you want to use them: 

```
// User
import { UserComponent } from '../user/user.component';
import { UserListComponent } from '../user/user-list.component';
import { UserService } from '../user/user.service';

// App
import { AppComponent } from '../app/app.component';

// Pets
import { PetComponent } from '../pet/pet.component';
import { PetListComponent } from '../pet/pet-list.component';
import { PetService } from '../pet/pet.service';
import { DogDirective} from '../pet/dog.directive';


```

A [relevant conversation](https://twitter.com/JimTheDev/status/646011222853156864).

Thoughts?

**Comment by bkinsey808** [comment]
Makes sense. Especially as a project grows. Thanks!

**Comment by mpint** [comment]
looks like you did the refactor @bkinsey808, can you confirm it's what you had in mind @jimthedev?

**Comment by bkinsey808** [comment]
@mpint I didn't fully refactor yet. I refactored the paths but not the file names or the component names. I will consider fully implementing @jimthedev 's full proposal when I get a chance because it does make sense overall to me, especially if the project gets big with many files.

**Comment by mpint** [comment]
@bkinsey808 cool, I think there may be a misunderstanding in the path naming convention though.  Would like @jimthedev to confirm.

I was under the impression he proposed to remove the `components` and `services` folders all together and replace them with baked in names like `nav/nav.component` and `nav/nav.service`

**Comment by jimthedev** [comment]
@mpint is correct. In my proposal there would cease to be folders but instead would be high level feature folders. Inside of a given feature (say, nav in this case) you'd have nav.component.ts or nav-list.component.ts

**Comment by bkinsey808** [comment]
I'm working on it right now. :)

**Comment by jimthedev** [comment]
👍

**Comment by mpint** [comment]
cool, in addition I'd like to propose a standard `<name>.template.html` convention as well as starting all sass files with an `_` to get them out of the way in the file structure, i.e. `_nav.scss`

then, a directory would look like:

```
../main/main
  ./_main.scss
  ./main.component.ts
  ./main.service.ts
  ./main.template.html
```

**Comment by bkinsey808** [comment]
@mpint @jimthedev guys I just did a push with the feature-wise layout. lemmee know what you think. Also there might be some errors leftover. Sorry I can't fully debug this right now, gotta run. Thank you both for your help. Happy hacking!

**Comment by mpint** [comment]
btw, awesome work @bkinsey808, it's great to see the new family in action!  

One other minor change I propose is to bring `app.ts` into the root of the `src` so that the `System` call in `index.html` can read: `System.import('app')`

**Comment by bkinsey808** [comment]
Yes sounds great. Feel free to make a PR. Thanks so much :)

**Comment by jimthedev** [comment]
I'd go the other way and make app just like any other component having the
same folder structure using feature. App is just a component like any other
and actually ng2 will support multi app bootstrapping in the same page so
you could theoretically have app and app-addon both bootstrapped.

**Comment by mpint** [comment]
Cool, thanks for the info @jimthedev.  About to make another PR...just trying to figure out why the sass gulp task is broken.

**Comment by bkinsey808** [comment]
I think this issue is resolved. I like the idea of feature-wise directory layout and all the rest of the great ideas. Thanks so much!

**Comment by jimthedev** [comment]
My pleasure. Thanks for being open to this.
