### ISSUE TITLE
string interpolation

### ISSUE THREAD

**Issue by bkinsey808** [bkinsey808/bk-fullstack-ts#5]
@jimthedev Is interpolation working for you? I can't get it to work on any component other than the app component.

String interpolation is putting stuff inside {{ here }} in the angular html templates.

Did something break or did this never work?

**Comment by jimthedev** [comment]
@bkinsey808 is this something that still isn't working for you? It looks like it is working in the current example for me. Perhaps I am missing something. Do you have an example where it is broken?

**Comment by bkinsey808** [comment]
Working now for me too. Thanks. I'll close this issue.
